// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

/**
 * A user.
 */
export interface User {
  /**
   * The unique identifier for this user.
   * @type A GUID string.
   * @readonly This attribute is managed automatically by the system.
   */
  id: string;
  /**
   * The date and time this user was created.
   * @readonly This attribute is managed automatically by the system.
   */
  createdAt?: string;
  /**
   * The date and time this user was last updated.
   * @readonly This attribute is managed automatically by the system.
   */
  updatedAt?: string;
  /**
   * The date and time this user was deleted.
   * @readonly This attribute is managed automatically by the system.
   */
  deletedAt?: string;
  /**
   * The date and time this user version was created, or "LATEST" for the most recent version.
   * @readonly This attribute is managed automatically by the system.
   */
  version?: string;
  /**
   * The type for this user.
   * @readonly This attribute is managed automatically by the system.
   */
  type?: string;
  /**
   * A first-name.
   */
  firstName?: string;
  /**
   * A last-name.
   */
  lastName?: string;
}
