import { execSync } from "child_process";
import { App, Stack } from "aws-cdk-lib";

const branchName = execSync("git rev-parse --abbrev-ref HEAD").toString("utf8").replace(/[\n\rs]+$/, "");
const branchPath = branchName.split("/");
const buildId = branchPath[branchPath.length - 1];

const serviceName = "company";

const app = new App();
const stack = new Stack(app, `${serviceName}-${buildId}`);
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
