// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

/**
 * A saas-identity.
 */
export interface SaasIdentity {
  /**
   * The type for this record.
   * @readonly This attribute is managed automatically by the system.
   */
  type?: string;
  /**
   * A actor-type.
   */
  actorType?: string;
  /**
   * A actor.
   */
  actor?: string;
  /**
   * A scope.
   */
  scope?: string;
}
