// import { ??? } from "aws-lambda";
import {
  DynamoTenant,
  CreateTenantInput,
  CreateTenantOutput,
  Tenant,
} from "../../../ts/tenant";
import { createTenant } from "../../commands/create-tenant";

export const handler = async (
  event: any
): Promise<CreateTenantOutput> => {
  return createTenant(event.arguments);
};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
