// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

export interface Group {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: string;
  version?: string;
  type?: string;
  name: string;
}
