// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

export interface User {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: string;
  version?: string;
  type?: string;
  firstName?: string;
  lastName?: string;
}
