import { AppSyncResolverEvent } from "aws-lambda";
import { CreateTenantInput, CreateTenantOutput } from "../../../shapes/tenant";

export const handler = async (
  event: AppSyncResolverEvent<CreateTenantInput>
): Promise<CreateTenantOutput> => {
  return { id: "foo" };
};

// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
