import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, DeleteCommand } from "@aws-sdk/lib-dynamodb";
import {
  Error,
  DeleteUserInput,
  DeleteUserOutput,
  Response,
} from "../../types/user";

// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
