import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, UpdateCommand } from "@aws-sdk/lib-dynamodb";
import {
  Error,
  UpdateUserInput,
  UpdateUserOutput,
  Response,
} from "../../types/user";

// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
