import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, GetCommand } from "@aws-sdk/lib-dynamodb";
import { marshall, unmarshall } from "@aws-sdk/util-dynamodb";
import { AppSyncResolverEvent } from "aws-lambda";
import {
  DynamoTenant,
  ReadTenantInput,
  ReadTenantOutput,
  Tenant,
} from "../../../ts/tenant";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);
const tableName = "tenant";

export const handler = async (
  event: AppSyncResolverEvent<ReadTenantInput, any>
): Promise<ReadTenantOutput> => {
  /**
   * Initialize the shape dynamo expects. This may differ from the externally
   * exposed shape.
   */
  let tenant: DynamoTenant = {
    t: "Tenant",
    v: "LATEST",
    id: event.arguments.id,
  };

  /**
   * Add key values to the shape.
   */
  tenant.pk = tenant.id;
  tenant.sk = tenant.t + "#" + tenant.v;

  /**
   * Build the key for this item.
   */
  const key = {
    pk: tenant.pk,
    sk: tenant.sk,
  };

  /**
   * Try to read the data.
   */
  const result = await dynamo.send(
    new GetCommand({
      TableName: tableName,
      Key: marshall(key),
    })
  );
  if (result.Item) {
    return unmarshall(result.Item) as Tenant;
  }
  throw new Error("item not found");
};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
