// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

export interface CreateGroupInput {
  foo: string;
}

export interface CreateGroupInput {
  foo: string;
}

export const handler = async (event: any) => {
  return true;
};
