import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, PutCommand } from "@aws-sdk/lib-dynamodb";
import { v4 as uuidv4 } from "uuid";
import {
  Error,
  CreateCompanyInput,
  CreateCompanyOutput,
  Response,
} from "../../types/company";

// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
