import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, DeleteCommand } from "@aws-sdk/lib-dynamodb";
import {
  Error,
  DeleteCompanyInput,
  DeleteCompanyOutput,
  Response,
} from "../../types/company";

// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
