import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, GetCommand } from "@aws-sdk/lib-dynamodb";
import {
  Error,
  GetCompanyInput,
  GetCompanyOutput,
  Response,
} from "../../types/company";

// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
