import { AppSyncResolverEvent } from "aws-lambda";
import { CreateUserInput, CreateUserOutput } from "../../../shapes/user";

export const handler = async (
  event: AppSyncResolverEvent<CreateUserInput>
): Promise<CreateUserOutput> => {
  return { id: "foo" };
};

// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
