import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, PutCommand } from "@aws-sdk/lib-dynamodb";
import { marshall, unmarshall } from "@aws-sdk/util-dynamodb";
import { v4 as uuidv4 } from "uuid";
import {
  DynamoTenant,
  ImportTenantInput,
  ImportTenantOutput,
} from "../../../ts/tenant";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);
const tableName = "tenant";

export const importTenant = async (
  input: ImportTenantInput
): Promise<ImportTenantOutput> => {
  /**
   * Initialize the shape dynamo expects. This may differ from the externally
   * exposed shape.
   */
  let tenant: DynamoTenant = {
    id: uuidv4(),
    t: "Tenant",
    v: "LATEST",
    cd: new Date().toISOString(),
    id: input.id,
  };

  /**
   * Add key values to the shape.
   */
  tenant.pk = tenant.id;
  tenant.sk = tenant.t + "#" + tenant.v;

  /**
   * Try to put the data in dynamo.
   */
  const result = await dynamo.send(
    new PutCommand({
      TableName: tableName,
      Item: marshall(tenant),
    })
  );
};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
