import { Context, DynamoDBPutItemRequest, util } from "@aws-appsync/utils";

export function request(ctx: Context<any>): DynamoDBPutItemRequest {}

export function response(
  ctx: Context<MutationCreatePostArgs, object, object, object, Post>
) {
  return ctx.result;
}

// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
