import { AppSyncResolverEvent } from "aws-lambda";
import { CreateGroupInput, CreateGroupOutput } from "../../../shapes/group";

export const handler = async (
  event: AppSyncResolverEvent<CreateGroupInput>
): Promise<CreateGroupOutput> => {
  return { id: "foo" };
};

// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
