import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, PutCommand } from "@aws-sdk/lib-dynamodb";
import { marshall, unmarshall } from "@aws-sdk/util-dynamodb";
import { v4 as uuidv4 } from "uuid";
import {
  DynamoTenant,
  CreateTenantInput,
  CreateTenantOutput,
  Tenant,
} from "../../ts/tenant";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);
const tableName = "tenant";

export const createTenant = async (
  input: CreateTenantInput
): Promise<CreateTenantOutput> => {
  /**
   * Initialize the shape dynamo expects. This may differ from the externally
   * exposed shape.
   */
  let tenant: DynamoTenant = {
    id: uuidv4(),
    t: "Tenant",
    v: "LATEST",
    cd: new Date().toISOString(),
    name: input.name,
  };

  /**
   * Add key values to the shape.
   */
  tenant.pk = tenant.id;
  tenant.sk = tenant.t + "#" + tenant.v;

  /**
   * Build the key for this item.
   */
  const key = {
    pk: tenant.pk,
    sk: tenant.sk,
  };

};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
