import { deleteGroup } from "./delete-group";
import {
  DeleteGroupInput,
} from "../../types";

test("Smoke test", async () => {
  const fixture : DeleteGroupInput = {
    id: 'foo',
  };
  const result = await deleteGroup(fixture);
  expect(result).toBeTruthy();
})
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
