import { deleteUser } from "./delete-user";
import {
  DeleteUserInput,
} from "../../types";

test("Smoke test", async () => {
  const fixture : DeleteUserInput = {
    id: 'foo',
  };
  const result = await deleteUser(fixture);
  expect(result).toBeTruthy();
})
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
