import { getUser } from "./get-user";
import {
  GetUserInput,
} from "../../types";

test("Smoke test", async () => {
  const fixture : GetUserInput = {
    id: 'foo',
  };
  const result = await getUser(fixture);
  expect(result).toBeTruthy();
})
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
