import { getGroup } from "./get-group";
import {
  GetGroupInput,
} from "../../types";

test("Smoke test", async () => {
  const fixture : GetGroupInput = {
    id: 'foo',
  };
  const result = await getGroup(fixture);
  expect(result).toBeTruthy();
})
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
