import { updateUser } from "./update-user";
import {
  UpdateUserInput,
} from "../../types";

test("Smoke test", async () => {
  const fixture : UpdateUserInput = {
    id: 'foo',
    firstName: 'foo',
    lastName: 'foo',
  };
  const result = await updateUser(fixture);
  expect(result).toBeTruthy();
})
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
