import { updateGroup } from "./update-group";
import {
  UpdateGroupInput,
} from "../../types";

test("Smoke test", async () => {
  const fixture : UpdateGroupInput = {
    id: 'foo',
    name: 'foo',
  };
  const result = await updateGroup(fixture);
  expect(result).toBeTruthy();
})
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
