import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, PutCommand } from "@aws-sdk/lib-dynamodb";
import {
  CreateTenantInput,
  CreateTenantOutput,
  Response,
  CreateTenantInputDynamo,
} from "../../types";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);

export const createTenant = async (
  input: Required<CreateTenantInput>
): Promise<Response<CreateTenantOutput>> => {

  const {
    name,
  } = input;

  const n = name;

  const result = await dynamo.send(
    new PutCommand({
      TableName: "tenant",
      Item: {
        n,
      } as CreateTenantInputDynamo,
    })
  );

};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
