import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, PutCommand } from "@aws-sdk/lib-dynamodb";
import {
  CreateActorInput,
  CreateActorOutput,
  Response,
} from "../../types";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);

export const createActor = async (
  input: Required<CreateActorInput>
): Promise<Response<CreateActorOutput>> => {

  const {
    pk,
    sk,
    idx,
    id,
    type,
    version,
    createdAt,
    updatedAt,
    deletedAt,
    firstName,
    lastName,
  } = input;

  // const pk = undefined;
  // const sk = undefined;
  // const idx = undefined;
  const id = uuidv4();
  const t = "actor";
  const v = "LATEST";
  const cd = new Date().toISOString();
  const ud = new Date().toISOString();
  const dd = new Date().toISOString();
  const fn = firstName;
  const ln = lastName;

  const result = await dynamo.send(
    new PutCommand({
      TableName: "tenant",
      Item: {
        pk,
        sk,
        idx,
        id,
        t,
        v,
        cd,
        ud,
        dd,
        fn,
        ln,
      },
    })
  );

};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
