import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, PutCommand } from "@aws-sdk/lib-dynamodb";
import { marshall, unmarshall } from "@aws-sdk/util-dynamodb";
import {
  DynamoTenant,
  Tenant
} from "../../types";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);
const tableName = "tenant";

export const createTenant = async (
  input: Tenant
): Promise<Tenant> => {
  /**
   * Initialize the shape dynamo expects. This may differ from the externally
   * exposed shape.
   */
  const item: DynamoTenant = {
    id: uuidv4(),
    t: "Tenant",
    v: "LATEST",
    cd: new Date().toISOString(),
  };

};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
