import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, UpdateCommand } from "@aws-sdk/lib-dynamodb";
import {
  DeleteActorInput,
  DeleteActorOutput,
  Response,
} from "../../types";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);

export const deleteActor = async (
  input: Required<DeleteActorInput>
): Promise<Response<DeleteActorOutput>> => {

  const {
    pk,
    sk,
    idx,
    id,
    type,
    version,
    createdAt,
    updatedAt,
    deletedAt,
    firstName,
    lastName,
  } = input;

  // const pk = undefined;
  // const sk = undefined;
  // const idx = undefined;
  const id = uuidv4();
  const t = "actor";
  const v = "LATEST";
  const cd = new Date().toISOString();
  const ud = new Date().toISOString();
  const dd = new Date().toISOString();
  const fn = firstName;
  const ln = lastName;

  const result = await dynamo.send(
    new UpdateCommand({
      TableName: "tenant",
      UpdateExpression: "set #pk = :pk, #sk = :sk, #idx = :idx, #id = :id, #t = :t, #v = :v, #cd = :cd, #ud = :ud, #dd = :dd, #fn = :fn, #ln = :ln",
      ExpressionAttributeValues: {
        ":pk": pk,
        ":sk": sk,
        ":idx": idx,
        ":id": id,
        ":t": t,
        ":v": v,
        ":cd": cd,
        ":ud": ud,
        ":dd": dd,
        ":fn": fn,
        ":ln": ln,
      },
      ExpressionAttributeNames: {
        "#pk": "pk",
        "#sk": "sk",
        "#idx": "idx",
        "#id": "id",
        "#t": "t",
        "#v": "v",
        "#cd": "cd",
        "#ud": "ud",
        "#dd": "dd",
        "#fn": "fn",
        "#ln": "ln",
      },
      Key: {
        pk,
        sk,
      },
    })
  );

};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
