import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, DeleteCommand } from "@aws-sdk/lib-dynamodb";
import { marshall, unmarshall } from "@aws-sdk/util-dynamodb";
import {
  DynamoTenant,
  DynamoKey,
  Tenant
} from "../../types";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);

export const deleteTenant = async (
  input: Required<Tenant>
): Promise<Tenant> => {
  /**
   * Initialize the shape dynamo expects. This may differ from the externally
   * exposed shape.
   */
  const item: Required<Pick<DynamoTenant, "t" | "v" | "dd" | "n">> = {
    t: "Tenant",
    v: "LATEST",
    dd: new Date().toISOString(),
    n: input.name,
  };

  /**
   * Add key values to the shape.
   */
  const key: DynamoKey = {
    pk: item.id,
    sk: item.t + "#" + item.v,
  };

  const result = await dynamo.send(
    new DeleteCommand({
      TableName: "tenant",
      Key: marshall(key),
    })
  );

  return item as Tenant;
};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
