import { deleteTenant } from "./delete-tenant";
import {
  DeleteTenantInput,
} from "../../types";

test("Smoke test", async () => {
  const fixture : DeleteTenantInput = {
    id: 'foo',
  };
  const result = await deleteTenant(fixture);
  expect(result).toBeTruthy();
})
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
