import { deleteActor } from "./delete-actor";
import {
  DeleteActorInput,
} from "../../types";

test("Smoke test", async () => {
  const fixture : DeleteActorInput = {
    id: 'foo',
  };
  const result = await deleteActor(fixture);
  expect(result).toBeTruthy();
})
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
