import { getTenant } from "./get-tenant";
import {
  GetTenantInput,
} from "../../types";

test("Smoke test", async () => {
  const fixture : GetTenantInput = {
    id: 'foo',
  };
  const result = await getTenant(fixture);
  expect(result).toBeTruthy();
})
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
