import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, GetCommand } from "@aws-sdk/lib-dynamodb";
import { marshall, unmarshall } from "@aws-sdk/util-dynamodb";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);

/**
 * A gereric type
 */
export interface GetActorInput {
  /**
   * The unique identifier for this record.
   * @type A GUID string.
   * @readonly This attribute is managed automatically by the system.
   */
  id?: string;
}

/**
 * A gereric type
 */
export interface GetActorOutput {
  /**
   * The unique identifier for this record.
   * @type A GUID string.
   * @readonly This attribute is managed automatically by the system.
   */
  id?: string;
  /**
   * The type for this record.
   * @readonly This attribute is managed automatically by the system.
   */
  type?: string;
  /**
   * The version of this record
   * @default "LATEST"
   * @readonly This attribute is managed automatically by the system.
   */
  version?: string;
  /**
   * The date and time this record was created.
   * @readonly This attribute is managed automatically by the system.
   */
  createdAt?: string;
  /**
   * The date and time this record was last updated.
   * @readonly This attribute is managed automatically by the system.
   */
  updatedAt?: string;
  /**
   * The date and time this record was deleted.
   * @readonly This attribute is managed automatically by the system.
   */
  deletedAt?: string;
  /**
   * A actor-name.
   */
  actorName?: string;
}

interface GetActorInputDynamo {
  id?: string;
  t?: string;
  v?: string;
  pk?: string;
  sk?: string;
  idx?: string;
}

interface GetActorOutputDynamo {
  id?: string;
  t?: string;
  v?: string;
  cd?: string;
  ud?: string;
  dd?: string;
  an?: string;
  pk?: string;
  sk?: string;
  idx?: string;
}

export const getActor = async (
  input: Required<GetActorInput>
): Promise<GetActorOutput> => {

  const {
    id
  } = input;

  const id = generated;
  const t = "actor";
  const v = "LATEST";
  const pk = id;
  const sk = t + "#" + v;
  // const idx = undefined;

  const item: GetActorInputDynamo = {
    id,
    t,
    v,
    pk,
    sk,
    // idx,
  };

};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
