import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, GetCommand } from "@aws-sdk/lib-dynamodb";
import {
  GetTenantInput,
  GetTenantOutput,
  Response,
} from "../../types";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);

export const getTenant = async (
  input: Required<GetTenantInput>
): Promise<Response<GetTenantOutput>> => {

  const {
    pk,
    sk,
    idx,
    id,
    type,
    version,
    createdAt,
    updatedAt,
    deletedAt,
    name,
  } = input;

  // const pk = undefined;
  // const sk = undefined;
  // const idx = undefined;
  const id = uuidv4();
  const t = "tenant";
  const v = "LATEST";
  const cd = new Date().toISOString();
  const ud = new Date().toISOString();
  const dd = new Date().toISOString();
  const n = name;

  const result = await dynamo.send(
    new GetCommand({
      TableName: "tenant",
      Key: {
        pk,
        sk,
      },
    })
  );

};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
