import { getActor } from "./get-actor";
import {
  GetActorInput,
} from "../../types";

test("Smoke test", async () => {
  const fixture : GetActorInput = {
    id: 'foo',
  };
  const result = await getActor(fixture);
  expect(result).toBeTruthy();
})
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
