import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, GetCommand } from "@aws-sdk/lib-dynamodb";
import {
  GetTenantInput,
  GetTenantOutput,
  Response,
  GetTenantInputDynamo,
} from "../../types";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);

export const getTenant = async (
  input: Required<GetTenantInput>
): Promise<Response<GetTenantOutput>> => {

  const {
    id,
  } = input;

  const t = "tenant";
  const v = "LATEST";
  const pk = id.toLowerCase();
  const sk = t.toLowerCase() + "#" + v.toLowerCase();
  // const idx = undefined;

  const result = await dynamo.send(
    new GetCommand({
      TableName: "tenant",
      Key: {
        pk,
        sk,
      },
    })
  );

};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
