import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, GetCommand } from "@aws-sdk/lib-dynamodb";
import {
  GetActorInput,
  GetActorOutput,
  Response,
  GetActorInputDynamo,
} from "../../types";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);

export const getActor = async (
  input: Required<GetActorInput>
): Promise<Response<GetActorOutput>> => {

  const {
  } = input;


  const result = await dynamo.send(
    new GetCommand({
      TableName: "tenant",
      Key: {
        pk,
        sk,
      },
    })
  );

};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
