import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, PutCommand } from "@aws-sdk/lib-dynamodb";
import { marshall, unmarshall } from "@aws-sdk/util-dynamodb";
import {
  DynamoActor,
  DynamoKey,
  Actor
} from "../../types";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);

export const importActor = async (
  input: Required<Actor>
): Promise<Actor> => {
  /**
   * Initialize the shape dynamo expects. This may differ from the externally
   * exposed shape.
   */
  const item: Required<Pick<DynamoActor, "t" | "an">> = {
    t: "Actor",
    an: input.actorName,
  };

  /**
   * Add key values to the shape.
   */
  const key: DynamoKey = {
    pk: item.id,
    sk: item.t + "#" + item.v,
  };

  const result = await dynamo.send(
    new PutCommand({
      TableName: "tenant",
      Item: marshall({ ...item, ...key }),
    })
  );

  return item as Actor;
};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
