import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, PutCommand } from "@aws-sdk/lib-dynamodb";
import {
  ImportTenantInput,
  ImportTenantOutput,
  Response,
  ImportTenantInputDynamo,
} from "../../types";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);

export const importTenant = async (
  input: Required<ImportTenantInput>
): Promise<Response<ImportTenantOutput>> => {

  const {
    name,
  } = input;

  const n = name;

  const result = await dynamo.send(
    new PutCommand({
      TableName: "tenant",
      Item: {
        n,
      } as ImportTenantInputDynamo,
    })
  );

};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
