import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, PutCommand } from "@aws-sdk/lib-dynamodb";
import {
  ImportTenantInput,
  ImportTenantOutput,
  Response,
  ImportTenantInputDynamo,
} from "../../types";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);

export const importTenant = async (
  input: Required<ImportTenantInput>
): Promise<Response<ImportTenantOutput>> => {

  const {
    id,
    name,
  } = input;

  const t = "tenant";
  const v = "LATEST";
  const cd = new Date().toISOString();
  const ud = new Date().toISOString();
  const n = name;
  const pk = id.toLowerCase();
  const sk = t.toLowerCase() + "#" + v.toLowerCase();
  // const idx = undefined;

  const result = await dynamo.send(
    new PutCommand({
      TableName: "tenant",
      Item: {
        id,
        t,
        v,
        cd,
        ud,
        n,
        pk,
        sk,
        idx,
      } as ImportTenantInputDynamo,
    })
  );

};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
