import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, PutCommand } from "@aws-sdk/lib-dynamodb";
import { marshall, unmarshall } from "@aws-sdk/util-dynamodb";
import {
  DynamoActor,
  Actor
} from "../../types";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);
const tableName = "tenant";

export const importActor = async (
  input: Actor
): Promise<Actor> => {
  /**
   * Initialize the shape dynamo expects. This may differ from the externally
   * exposed shape.
   */
  const item: DynamoActor = {
    t: "Actor",
  };

};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
