import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, PutCommand } from "@aws-sdk/lib-dynamodb";
import {
  ImportActorInput,
  ImportActorOutput,
  Response,
  ImportActorInputDynamo,
} from "../../types";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);

export const importActor = async (
  input: Required<ImportActorInput>
): Promise<Response<ImportActorOutput>> => {

  const {
    firstName,
    lastName,
  } = input;

  const fn = firstName;
  const ln = lastName;

  const result = await dynamo.send(
    new PutCommand({
      TableName: "tenant",
      Item: {
        fn,
        ln,
      } as ImportActorInputDynamo,
    })
  );

};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
