import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, UpdateCommand } from "@aws-sdk/lib-dynamodb";
import {
  UpdateTenantInput,
  UpdateTenantOutput,
  Response,
  UpdateTenantInputDynamo,
} from "../../types";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);

export const updateTenant = async (
  input: Required<UpdateTenantInput>
): Promise<Response<UpdateTenantOutput>> => {

  const {
    id,
    name,
  } = input;

  const t = "tenant";
  const v = "LATEST";
  const ud = new Date().toISOString();
  const n = name;
  const pk = id.toLowerCase();
  const sk = t.toLowerCase() + "#" + v.toLowerCase();
  // const idx = undefined;

  const result = await dynamo.send(
    new UpdateCommand({
      TableName: "tenant",
      UpdateExpression: "set #id = :id, #t = :t, #v = :v, #ud = :ud, #n = :n, #pk = :pk, #sk = :sk, #idx = :idx",
      ExpressionAttributeValues: {
        ":id": id,
        ":t": t,
        ":v": v,
        ":ud": ud,
        ":n": n,
        ":pk": pk,
        ":sk": sk,
        ":idx": idx,
      },
      ExpressionAttributeNames: {
        "#id": "id",
        "#t": "t",
        "#v": "v",
        "#ud": "ud",
        "#n": "n",
        "#pk": "pk",
        "#sk": "sk",
        "#idx": "idx",
      },
      Key: {
        pk,
        sk,
      },
    })
  );

};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
