import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, UpdateCommand } from "@aws-sdk/lib-dynamodb";
import { marshall, unmarshall } from "@aws-sdk/util-dynamodb";
import {
  DynamoTenant,
  DynamoKey,
  Tenant
} from "../../types";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);
const tableName = "tenant";

export const updateTenant = async (
  input: Tenant
): Promise<Tenant> => {
  /**
   * Initialize the shape dynamo expects. This may differ from the externally
   * exposed shape.
   */
  const item: DynamoTenant = {
    t: "Tenant",
    v: "LATEST",
    ud: new Date().toISOString(),
  };

  /**
   * Add key values to the shape.
   */
  const key: DynamoKey = {
    pk: item.id,
    sk: item.t + "#" + item.v,
  };

};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
