import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, UpdateCommand } from "@aws-sdk/lib-dynamodb";
import {
  UpdateActorInput,
  UpdateActorOutput,
  Response,
  UpdateActorInputDynamo,
} from "../../types";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);

export const updateActor = async (
  input: Required<UpdateActorInput>
): Promise<Response<UpdateActorOutput>> => {

  const {
    firstName,
    lastName,
  } = input;

  const fn = firstName;
  const ln = lastName;

  const result = await dynamo.send(
    new UpdateCommand({
      TableName: "tenant",
      UpdateExpression: "set #fn = :fn, #ln = :ln",
      ExpressionAttributeValues: {
        ":fn": fn,
        ":ln": ln,
      },
      ExpressionAttributeNames: {
        "#fn": "fn",
        "#ln": "ln",
      },
      Key: {
        pk,
        sk,
      },
    })
  );

};
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
