import { updateActor } from "./update-actor";
import {
  UpdateActorInput,
} from "../../types";

test("Smoke test", async () => {
  const fixture : UpdateActorInput = {
    id: 'foo',
    firstName: 'foo',
    lastName: 'foo',
  };
  const result = await updateActor(fixture);
  expect(result).toBeTruthy();
})
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
