import { createTenant } from "./create-tenant";
import {
  CreateTenantInput,
} from "../../types";

test("Smoke test", async () => {
  const fixture : CreateTenantInput = {
    name: 'foo',
    nickname: 'foo',
  };
  const result = await createTenant(fixture);
  expect(result).toBeTruthy();
})
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
