import { createTables, deleteTables, startDb, stopDb, } from "jest-dynalite";
import { createActor } from "./create-actor.ts";
import {
  CreateActorInput,
} from "../../types";

/**
 * Sometimes dynalite tests can require a little additional
 * time when you are running a lot of them in parallel.
 *
 * https://www.npmjs.com/package/jest-dynalite
 */
jest.setTimeout(10000);

/**
 * Starts and stops dynalite for each test
 *
 * https://www.npmjs.com/package/jest-dynalite
 */
beforeAll(startDb);
beforeEach(createTables);
afterEach(deleteTables);
afterAll(stopDb);

test("Smoke test", async () => {
  const fixture : CreateActorInput = {
    firstName: "foo",
    lastName: "foo",
  };
  const result = await createActor(fixture);
  const { data, errors, status } = result;
  console.log("createActor() Result:", JSON.stringify(result, null, 2));
  expect(data).toBeTruthy();
  expect(errors.length).toBe(0);
  expect(status).toBe(200);
  expect(data.name).toBe("foo");
})

// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
