import { createActor } from "./create-actor";
import {
  CreateActorInput,
} from "../../types";

test("Smoke test", async () => {
  const fixture : CreateActorInput = {
    firstName: 'foo',
    lastName: 'foo',
  };
  const result = await createActor(fixture);
  expect(result).toBeTruthy();
})
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
