import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, PutCommand } from "@aws-sdk/lib-dynamodb";
import { v4 as uuidv4 } from "uuid";
import {
  CreateActorInput,
  CreateActorOutput,
  Response,
} from "../../types";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);

export const createActor = async (
  input: Required<CreateActorInput>
): Promise<Response<CreateActorOutput>> => {

  const {
    firstName,
    lastName,
  } = input;

  const fn = firstName;
  const ln = lastName;

  const id = uuidv4();
  const t = "actor";
  const v = "LATEST";
  const cd = new Date().toISOString();
  const ud = new Date().toISOString();
  const pk = id.toLowerCase();
  const sk = t.toLowerCase() + "#" + v.toLowerCase();
  const idx = fn.toLowerCase() + "#" + ln.toLowerCase();

  const result = await dynamo.send(
    new PutCommand({
      TableName: "tenant",
      Item: {
        id,
        t,
        v,
        cd,
        ud,
        fn,
        ln,
        pk,
        sk,
        idx,
      },
    })
  );

};

// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
