import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, QueryCommand } from "@aws-sdk/lib-dynamodb";
import {
  Error,
  ListTenantsInput,
  ListTenantsOutput,
  ListResponse,
} from "../../types";

/**
 * Generate a DynamoDB client, configure it to use a local endpoint when needed
 * to support unit testing with dynalite.
 *
 * https://www.npmjs.com/package/jest-dynalite
 */
const config = {
  ...(process.env.MOCK_DYNAMODB_ENDPOINT && {
    endpoint: process.env.MOCK_DYNAMODB_ENDPOINT,
    sslEnabled: false,
    region: 'local',
  }),
}
const client = new DynamoDBClient(config);
const dynamo = DynamoDBDocumentClient.from(client);

export const listTenants = async (
  input: ListTenantsInput
): Promise<ListResponse<ListTenantsOutput>> => {

  /**
   * An error container in case we encounter problems along the way.
   */
  const errors = [] as Error[];

  /**
   * Assume things will go well (until they don't).
   */
  let status = 200;

  /**
   * Unwrap external inputs.
   */
  const {
    lookupText,
  } = input;

  const idx = lookupText;

  /**
   * Generate needed values.
   */
  const t = "tenant";
  const v = "latest";
  const sk = t.toLowerCase() + "#" + v.toLowerCase();

  const result = await dynamo.send(
    new QueryCommand({
      TableName: "tenant",
      IndexName: "lookup",
      KeyConditionExpression: "#sk = :sk and begins_with(#idx, :idx)",
      ExpressionAttributeValues: {
        ":sk": sk,
        ":idx": idx,
      },
      ExpressionAttributeNames: {
        "#sk": "sk",
        "#idx": "idx",
      },
      ReturnConsumedCapacity: "INDEXES",
    })
  );

  const data = result.Items
    ? result.Items.map((item) => {
        return {
          id: item.id,
          type: item.t,
          version: item.v,
          createdAt: item.cd,
          updatedAt: item.ud,
          name: item.n,
          nickname: item.nn,
        };
      }) : [];

  /**
   * Return result.
   */
  return {
    data,
    errors,
    status,
  };
};

// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
