import { updateTenant } from "./update-tenant";
import {
  UpdateTenantInput,
} from "../../types";

test("Smoke test", async () => {
  const fixture : UpdateTenantInput = {
    id: 'foo',
    name: 'foo',
    nickname: 'foo',
  };
  const result = await updateTenant(fixture);
  expect(result).toBeTruthy();
})
// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
