import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, DeleteCommand } from "@aws-sdk/lib-dynamodb";
import { marshall, unmarshall } from "@aws-sdk/util-dynamodb";
import { AppSyncResolverEvent } from "aws-lambda";
import {
  DynamoTenant,
  DeleteTenantInput,
  DeleteTenantOutput,
  Tenant,
} from "../../../ts/tenant";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);
const tableName = "tenant";

// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
